App\Entity\SmsAuto:
  constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: step
  properties:
    step:
      - NotBlank: ~

App\Entity\CustomerFiles:
  properties:
    customer_source:
      - NotBlank: ~
    name: 
      - NotBlank: ~
    cellphone:
      - Regex:
          pattern: /(?:(?:\+|00)33)\s*[67](?:[\s.-]*\d{2}){4}/
          message: Le numéro de téléphone n'est pas valide !

App\Entity\Alert:
  properties:
    name:
      - NotBlank: ~